### ISSUE TITLE
Make the bottoms nicer

### ISSUE THREAD

**Issue by laladiaz** [laladiaz/PA-MX013-trivia#1]
rounded, bigger and white. The color of the text might be neon of choosing

**Comment by erfanasadi** [comment]
i can make it nicer

**Comment by LouArlo** [comment]
Va! Lala

**Comment by laladiaz** [comment]
> i can make it nicer

Thanks erfanasadi. This was an experiment as I didn't know how to make this work! 🙃 LouArlo is a friend who is helping me to understand! so we can start collaborate and open issues and integrate to the open source community! Thanks again! 😄
